# Generated by Django 4.0.3 on 2022-03-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='perosnAge',
            new_name='perosonAge',
        ),
    ]
