# Generated by Django 4.0.3 on 2022-03-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_rename_perosnage_person_perosonage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='perosonAge',
            new_name='personAge',
        ),
    ]
